# -*- coding: utf-8 -*-
"""NLPCWF_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEhqaVaEV2fv3Lg06URTjWMQq-IpAg9y
"""

# Commented out IPython magic to ensure Python compatibility.

import streamlit as st
from transformers import pipeline, AutoTokenizer, AutoModelForQuestionAnswering

def load_model():
    # Load DistilBERT model and tokenizer
    tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased-distilled-squad")
    model = AutoModelForQuestionAnswering.from_pretrained("distilbert-base-cased-distilled-squad", return_dict=True)

    # Question answering pipeline
    qa_pipe = pipeline("question-answering", model=model, tokenizer=tokenizer)
    return qa_pipe

qa_pipe = load_model()

# Streamlit app
def main():
    st.title("🍎 Hello Kitty Q&A 🍎")

    # Hello Kitty context
    context = "Hello Kitty, is a fictional character created by Yuko Shimizu, currently designed by Yuko Yamaguchi, and owned by the Japanese company Sanrio. Hello Kitty is a personification of a Japanese Bobtail cat with a red bow and no visible mouth and was created in 1974. Her height is described as five apples and her weight as three apples. Spokespeople for Sanrio have said that Hello Kitty has no mouth, as they want people to project their feelings onto the character and be happy or sad together with Hello Kitty. "

    # User input
    question = st.text_area("Ask me about Hello Kitty!", value="")

    # Answer button
    if st.button("Get Answer"):
        # If input is not empty
        if question.strip() != "":
            
            # Get the answer using the pipeline
            answer = qa_pipe(question=question, context=context)

            # Display the answer
            st.markdown(f"≽ ^ • ⩊ • ^ ≼ 🍎 {answer['answer']} 🍎 ≽ ^ • ⩊ • ^ ≼")
            st.info(f"Confidence: {answer['score']}")

if __name__ == "__main__":
    main()


